import { getServerSession } from "next-auth"
import SessionProvider from "./components/SessionProvider";
import NavMenu from "./components/NavMenu";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body >
        <SessionProvider session={session} >
          <main className="mx-auto max-w-5xl flex gap-2">

            <NavMenu />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
